[general]
import = ["~/.config/alacritty/themes/themes/gruvbox_material_hard_dark.toml"]

[env]
TERM = "xterm-256color"

[window]
opacity = 0.6
dynamic_padding = true
blur = true

[font]
size = 12

## `fc-list`
[font.normal]
family = "JetBrainsMonoNerdFontMono"
style = "Regular"
